extends: "airbnb-base"

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true

rules:
  arrow-body-style: 0
  new-cap: 0
  no-use-before-define: ["error", { "functions": false, "classes": true }]

settings:
  import/resolver: webpack
