extends: airbnb-base

parser: babel-eslint

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true

rules:
  new-cap: 0
  no-use-before-define: ["error", { "functions": false, "classes": true }]

settings:
  import/resolver: webpack
