language: node_js
notifications:
  email:
    recipients:
      - nickjohnson.dev@gmail.com
node_js: 8
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run lint
  - yarn run testonce
  - yarn run build
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov'
  - npx framer-cli publish aria.framerfx --public --yes
