yarnPath: '.yarn/releases/yarn-berry.cjs'
packageExtensions:
  '@storybook/react@*':
    peerDependencies:
      '@babel/core': '*'
      'babel-loader': '*'
  '@typescript-eslint/eslint-plugin@*':
    peerDependencies:
      'eslint': '*'
  '@typescript-eslint/parser@*':
    peerDependencies:
      'eslint': '*'
  'eslint-config-react-app@*':
    peerDependencies:
      'babel-eslint': '*'
      'eslint': '*'
      'eslint-plugin-flowtype': '*'
      'eslint-plugin-import': '*'
      'eslint-plugin-jsx-a11y': '*'
      'eslint-plugin-react': '*'
      'eslint-plugin-react-hooks': '*'
